### ISSUE TITLE
Slow for large folders

### ISSUE THREAD

**Issue by mausworks** [anufrievroman/waypaper#1]
Thanks for a great project—it's exactly what I've been looking for! 🙌

Waypaper seems to take a considerable amount of time—around 20 seconds—to open if I use my `~/wallpaper/highres`  folder (it contains ~300 images that are 3440x1440 or bigger). I'm guessing it's attempting to read all the images to display the thumbnails.

It would be great if the thumbnails could either be cached or the images could be lazy-loaded.

**Comment by anufrievroman** [comment]
Hi, thank you for your interest to the project!
You're definitely right, loading time is currently the main problem. Basically it happens because it needs to read and resize each image.

 Unfortunately, I am such a noob at GTK that I was unable to even simply load the app first and display some loading screen. Currently, I aim to make some sort of lazy loading first, so that the images appear as they are loaded (I think I am not far from this goal). Then, implementing caching (I need to check what's a common practice for that).

If you or anyone here has experience with GTK interface loading, I'd gladly recieve an advice or at least some minimal working example/tutorial.

**Comment by mausworks** [comment]
Awesome stuff! I will upgrade and test it out when I get back home in a week or so!

**Comment by anufrievroman** [comment]
Hi, in version 1.6 with 09bdfaabbe5babad75afbb9607f33dd7d288dfd5 I implemented caching. For me, it works pretty well. It will cache the folder for some time the very first time, and all subsequent times it loads instantly. Please test :)

**Comment by mausworks** [comment]
I'm back home. This works great now, so I'll close this issue! 

Thanks a lot for this project again, and thanks a lot for the quick turnaround!
