### ISSUE TITLE
Ability to select transition settings when using 'swww' as a backend

### ISSUE THREAD

**Issue by Gylvaris** [anufrievroman/waypaper#20]
I do not know if there is such a possibility, but I do not see it anywhere. I think since swww is accepted as a backend, a great option would be to be able to customize how transitions work!

**Comment by anufrievroman** [comment]
Hi, thank you for the suggestion.
Basically, `swww` has many transition options, but since the app is only to change the wallpaper here and now, the user will in practice only see this animation once, when user clicks on the wallpaper of choice. I mean, the main function of transitions in `swww`, is when wallpapers are changing automatically, and you can enjoy this animation every once in a while, but in case of `waypaper`, you'd see this animation only once. Not sure if it is worth implementing this option (or several options that will take lots of space) just for this purpose, as I'd like to keep the interface minimal.

**Comment by anufrievroman** [comment]
One compromise may be that I can add this option accessible through config file. That is, if you really like a certain transition, you'd be able to set it (or several parameters) in the config of `waypaper` but not in gui.

**Comment by Gylvaris** [comment]
I understand as much as possible, and it makes sense, I gave such a suggestion because I personally have a problem to make animations work at my place. Only when I change the wallpaper with a command, when I try with a script something doesn't want to work

**Comment by anufrievroman** [comment]
@Gylvaris but you know, if you are really interested in `swww` there is another project from @0bCdian called [Waypaper Engine](https://github.com/0bCdian/Waypaper-Engine), there you can get all the options of `swww` via gui.

**Comment by anufrievroman** [comment]
Hi, I implemented the ability to select the transition, but only in the config (I am still thinking how to expand GUI interface without cluttering it much. You can add `swww_transition = wave` or any other supported transition to your config. It will be available in 2.0.3. Happy new year!

**Comment by anufrievroman** [comment]
I'll assume that's okay then. Feel free to reopen the issue is something is not right.
