### ISSUE TITLE
Installation on openSUSE

### ISSUE THREAD

**Issue by cprin21** [anufrievroman/waypaper#30]
Does not install via pipx due to a problem with cairo.

**Comment by anufrievroman** [comment]
Thank you for reporting. Do you mean that on Arch pipx works or pipx broken everywhere? Could you please show exact error?

**Comment by anufrievroman** [comment]
To me, it works fine, so I wonder what might be a specific problem...
![image](https://github.com/anufrievroman/waypaper/assets/42904990/726368c2-0824-4252-add3-aef24e82b5be)

**Comment by PierreBorine** [comment]
Had the same issue, pycairo failed to build when installing waypaper with pipx.
Resolved by installing the `python311-pycairo-devel` package on openSUSE TW then `python311-gobject-devel` for gobject to build too.

**Comment by anufrievroman** [comment]
To be honest, I am not even sure why `cairo` is required at all, as it's not a dependence. Is this required for `gobject` or `Pillow`?

**Comment by ThomChroma** [comment]
Same here on Tumbleweed, I guess it's only due to how pycairo is packaged by openSUSE.
As to why it's required, according to the log `Package 'cairo', required by 'virtual:world', not found`.

**Comment by ThomChroma** [comment]
Well it doesn't really need a fix in the end, that's just how things are on openSUSE: instead of having big packages we have several smaller ones and sometimes we need to install some *-devel.

But you were wondering why cairo is required so if `virtual:world` refers to something you can get rid of, it would be even better. If not then it's not an issue and you can close this one IMO 👍

**Comment by anufrievroman** [comment]
No clue what the `virual:world` might mean or refer to, nothing like this in the code. Okay, thank you for the insides. I'll update the docs and close this issue.
