### ISSUE TITLE
"waypaper --restore" restores image, but not config settings for image

### ISSUE THREAD

**Issue by jjramsey** [anufrievroman/waypaper#63]
`waypaper --restore` currently only restores the image but not the settings used to display the image stored in `config.ini`. I do have a 3-line fix for this here: https://github.com/anufrievroman/waypaper/pull/62

**Comment by anufrievroman** [comment]
Hi, thank you for the fix, and sorry for the delay, I've been away, I'll check it soon.

**Comment by anufrievroman** [comment]
I looked into it, and I am not sure if I fully understand the problem, maybe you could tell me a bit more about it? What specific settings are not restored?

The fix you proposed should not change anything it seems because at the point of your fix, the config file is fully read into `cf` object and the function that performs the `--restore` is fully aware of the config settings.

**Comment by jjramsey** [comment]
It doesn't restore the "fill" option, at the very least. Looks like the issue is more complicated than I thought. See my comment here: https://github.com/anufrievroman/waypaper/pull/62#issuecomment-2216098490

**Comment by jjramsey** [comment]
The pull request that was just merged fixes the problem.
